version: 2.1

jobs:
  build_arm64:
    machine:
      image: ubuntu-2204:current
      resource_class: arm.medium
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Getting dependencies
          command: sudo apt install ruby ruby-dev python3 python3-dev libz-dev libgit2-dev qtbase5-dev qttools5-dev libqt5xmlpatterns5-dev qtmultimedia5-dev libqt5multimediawidgets5 libqt5svg5-dev
      - run: 
          name: Build
          command: ./build.sh
      # - run:
      #     name: Run tests
      #     command: TODO

workflows:
  openvaf_workflow:
    jobs:
      - build_arm64